[package]
name = "ws-server"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
futures-util = "0.3.31"
tokio = {version="1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.2"
tungstenite = "0.26.2"
