services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: agenda

  rust-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/agenda"
