# Usa a imagem oficial do PostgreSQL
FROM postgres:latest

# Define as variáveis de ambiente para configuração do banco
ENV POSTGRES_USER=username
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=db

# Expondo a porta padrão do PostgreSQL
EXPOSE 5432
